// src/components/orgamisms/cv/profile.svelte
<script lang="ts">
	import IconCircleQuestionWavy from "@components/atoms/icons/IconCircleQuestionWavy.svelte";
	import IconGithub from "@components/atoms/icons/IconGithub.svelte";
	import IconLinkedin from "@components/atoms/icons/IconLinkedin.svelte";
	import { PROFILE } from "@model/cv";

	export let network: PROFILE;
	export let url: string;
	let clazz = "";
	export { clazz as class };
	function getIcon(network: PROFILE) {
		switch (network) {
			case PROFILE.LinkedIn:
				return IconLinkedin;
			case PROFILE.Github:
				return IconGithub;
			default:
				return IconCircleQuestionWavy;
		}
	}
</script>

<a
	href={url}
	class="transition-all flex flex-col justify-center items-center hover:text-red-600 dark:hover:text-red-300"
>
	<svelte:component this={getIcon(network)} />
	{network}
</a>

// src/components/cv/profile.tsx
import { IconLinkedin } from "@icons/IconLinkedin";
import { IconGithub } from "@icons/IconGithub";
import { IconCircleQuestionWavy } from "@icons/IconCircleQuestionWavy";

export type IProfile = HTMLAnchorElement & {
  network: string;
  username: string;
  url: string;
};

enum PROFILE {
  LinkedIn = "LinkedIn",
  Github = "Github",
  Unknown = "Unknown",
}

export function Profile({ network, url }: Omit<IProfile, "children">) {
  if (url === undefined) {
    return null;
  }

  return (
    <a
      href={url}
      className="transition-all flex flex-col justify-center items-center hover:text-red-600 dark:hover:text-red-300"
    >
      {getIcon(network as PROFILE, 8)}
      {network}
    </a>
  );
}

function getIcon(network: PROFILE, width: number): JSX.Element {
  switch (network) {
    case PROFILE.LinkedIn:
      return (
        <IconLinkedin className={`w-${width}`} aria-label="linkedin link" />
      );
    case PROFILE.Github:
      return <IconGithub className={`w-${width}`} aria-label="github link" />;
    default:
      return <IconCircleQuestionWavy className={`w-${width} `} />;
  }
}
