// src/components/orgamisms/cv/work/notableProject.svelte
<script lang="ts">
	import Typography from '@components/atoms/typography/typography.svelte';
	import classNames from 'classnames';
	import Technologies from './technologies.svelte';
	export let project: string;
	export let summary: string;
	export let highlights: string[] | undefined;
	export let technology: string[] | undefined;
	export let isLast: boolean;
</script>

<div
	class={classNames('pt-2 mb-4 pb-2', {
		'border-b border-b-red-100': !isLast
	})}
>
	<div class="mb-2">
		<span>Client:</span>
		<span>{project}</span>
	</div>

	<div class="pb-6">
		<p class="pb-6">{summary}</p>
		{#if highlights}
			<Typography variant="h3">Responsibilities</Typography>
			<ul>
				{#each highlights as highlight}
					<li>{highlight}</li>
				{/each}
			</ul>
		{/if}
	</div>
	<Technologies technologies={technology} />
</div>

// src/components/cv/work/notableProject.tsx
import { Technologies } from "@components/cv/work/technologies";
import classNames from "classnames";

type IProject = {
  project: string;
  summary: string;
  highlights?: string[];
  technology?: string[];
  isLast: boolean;
};

export function NotableProject({
  project,
  summary,
  highlights,
  technology,
  isLast,
}: IProject) {
  return (
    <div
      className={classNames("pt-2 mb-4 pb-2", {
        "border-b border-b-red-100": !isLast,
      })}
    >
      <div className="mb-2">
        <span>Client: </span>
        <span>{project}</span>
      </div>

      <div className="pb-6">
        <p className="pb-6">{summary}</p>
        {highlights && (
          <>
            <div>Responsibilities</div>
            <ul>
              {highlights?.map((highlight, index) => (
                <li key={index}>{highlight}</li>
              ))}
            </ul>
          </>
        )}
      </div>
      <Technologies technologies={technology} />
    </div>
  );
}
