// src/components/cv/work/notableProjectsContainer.tsx
import { NotableProject } from "./notableProject";

export type INotableProject = {
  project: string;
  summary: string;
  highlights?: string[];
  technology?: string[];
};
type INotableProjectsContainer = {
  notableProjects: INotableProject[];
};

export function NotableProjectsContainer({
  notableProjects,
}: INotableProjectsContainer) {
  if (!notableProjects) {
    return null;
  }

  return (
    <>
      <h2 className="block border-b border-b-red-100 mb-2 pb-0">
        Notable Projects
      </h2>
      {notableProjects.map(
        ({ project, technology, highlights, summary }, index) => (
          <NotableProject
            project={project}
            summary={summary}
            highlights={highlights}
            technology={technology}
            key={index}
            isLast={index === notableProjects.length - 1}
          />
        ),
      )}
    </>
  );
}

// src/components/orgamisms/cv/work/notableProjectsContainer.svelte
<script lang="ts">
	import Typography from '@components/atoms/typography/typography.svelte';
	import NotableProject from './notableProject.svelte';
	import type { INotableProject } from '@model/cv';
	export let notableProjects: INotableProject[] = [];
</script>

<Typography variant="h2" class="block border-b border-b-red-100 mb-2 pb-0"
	>Notable Projects</Typography
>

{#each notableProjects as { project, summary, highlights, technology }, i}
	<NotableProject
		{project}
		{summary}
		{highlights}
		{technology}
		isLast={i < notableProjects.length - 1}
	/>
{/each}
