// src/components/cv/skill.tsx
import { Technologies } from "@components/cv/work/technologies";

export type ISkill = {
  name: string;
  keywords: string[];
};

export function Skill(props: ISkill) {
  return (
    <div className="flex relative mb-2">
      <div className="mt-3 w-full">
        <div className="mb-2 text-lg text-center w-full my-4">
          <div className="transition-all block">{props.name}</div>

          <Technologies technologies={props.keywords} hideTitle={true} />
        </div>
      </div>
    </div>
  );
}

// src/components/orgamisms/cv/work/skill.svelte
<script lang="ts">
	import Technologies from "./technologies.svelte";
	export let name: string;
	export let keywords: string[];
</script>

<div class="flex relative mb-2">
	<div class="mt-3 w-full">
		<div class="mb-2 text-lg text-center w-full my-4">
			<div class="transition-all block">{name}</div>

			<Technologies technologies={keywords} hideTitle={true} />
		</div>
	</div>
</div>
