// src/components/cv/work/startEndDate.tsx
import classNames from "classnames";

type IStartEndDate = {
  startDate: string;
  endDate?: string;
  showEndDate?: boolean;
};
function getEndDate(endDate?: string, showEndDate = true) {
  return showEndDate
    ? endDate
      ? ` - ${new Date(endDate).toLocaleDateString(undefined, {
          weekday: undefined,
          year: "numeric",
          month: "short",
        })}`
      : " - Today"
    : "";
}

export function StartEndDate({
  endDate,
  startDate,
  showEndDate = true,
}: IStartEndDate) {
  return (
    <div className={classNames("", "absolute -top-3 right-0", "text-sm")}>
      <div className="flex flex-row justify-end">
        <div className="min-w-max">
          {new Date(startDate).toLocaleDateString(undefined, {
            weekday: undefined,
            year: "numeric",
            month: "short",
          })}
          {getEndDate(endDate, showEndDate)}
        </div>
      </div>
    </div>
  );
}

// src/components/orgamisms/cv/work/startEndDate.svelte
<script lang="ts">
	import Typography from '@components/atoms/typography/typography.svelte';
	import classNames from 'classnames';
	export let startDate: string;
	export let endDate: string | undefined;
	export let showEndDate = true;

	function getEndDate(endDate?: string, showEndDate = true) {
		return showEndDate
			? endDate
				? ` - ${new Date(endDate).toLocaleDateString(undefined, {
						weekday: undefined,
						year: 'numeric',
						month: 'short'
					})}`
				: ' - Today'
			: '';
	}
</script>

<div class={classNames('absolute top-3 right-3')}>
	<div class="flex flex-row justify-end">
		<div class="min-w-max">
			<Typography size="sm">
				{new Date(startDate).toLocaleDateString(undefined, {
					weekday: undefined,
					year: 'numeric',
					month: 'short'
				})}
				{getEndDate(endDate, showEndDate)}
			</Typography>
		</div>
	</div>
</div>
