// src/components/container/aboutSectionContainer.tsx
import type { MouseEvent, ReactNode } from "react";
import { useState } from "react";
import classNames from "classnames";
import { IconChevron } from "@icons/IconChevron";

type IAboutSectionContainer = {
  children: ReactNode;
  sectionTitle?: string;
  isCollapsable?: boolean;
  isInitiallyCollapsed?: boolean;
};

export function AboutSectionContainer({
  children,
  sectionTitle,
  isCollapsable = true,
  isInitiallyCollapsed = false,
}: IAboutSectionContainer) {
  const [isCollapsed, setIsCollapsed] = useState(isInitiallyCollapsed);

  function toggleVisibility(event: MouseEvent<HTMLDivElement>) {
    event.preventDefault();
    setIsCollapsed((ps) => !ps);
  }

  return (
    <section>
      <div
        className={classNames(
          "cursor-pointer",
          "flex",
          "relative",
          "justify-center",
          {
            "border-b border-red-300": isCollapsable,
          },
        )}
        onClick={toggleVisibility}
      >
        <SectionTitle title={sectionTitle} />
        <ExpandCollapseSectionButton
          isCollapsable={isCollapsable}
          isCollapsed={isCollapsed}
        />
      </div>
      <div className={classNames({ hidden: isCollapsed })}>{children}</div>
    </section>
  );
}

type IExpandCollapseSectionButton = {
  isCollapsable: boolean;
  isCollapsed: boolean;
};

function ExpandCollapseSectionButton({
  isCollapsable,
  isCollapsed,
}: IExpandCollapseSectionButton) {
  if (!isCollapsable) {
    return null;
  }

  return (
    <div
      className={classNames(
        "transition-all tracking-tighter absolute right-0 top-1/2 -translate-y-1/2  text-4xl",
        {
          "rotate-180": !isCollapsed,
        },
      )}
    >
      <IconChevron width={25} />
    </div>
  );
}

function SectionTitle({ title }: { title?: string }) {
  return title ? (
    <h2
      className="pl-2 text-center text-2xl"
      id={title?.toLowerCase().replaceAll(" ", "-")}
    >
      {title}
    </h2>
  ) : null;
}

// src/components/orgamisms/aboutSectionContainer.svelte
<script lang="ts">
	import classNames from "classnames";
	import SectionTitle from "@components/molecules/sectionTitle.svelte";
	import ExpandCollapseButton from "./expandCollapseButton.svelte";
	import { slide } from "svelte/transition";
	import { sineInOut } from "svelte/easing";
	export let sectionTitle = "";
	export let isCollapsable = true;
	export let isInitiallyCollapsed = false;
	$: isCollapsed = isInitiallyCollapsed;

	function toggleVisibility() {
		isCollapsed = !isCollapsed;
	}
</script>

<section class={classNames("border-b border-red-300")}>
	{#if isCollapsable}
		<button
			class={classNames(
				"cursor-pointer",
				"flex",
				"justify-center",
				"relative",
				"w-full",
				{
					"border-b border-red-300": isCollapsable
				}
			)}
			on:click={toggleVisibility}
		>
			<SectionTitle title={sectionTitle} />
			<ExpandCollapseButton {isCollapsed} />
		</button>
	{/if}
	{#if !isCollapsed}
		<!-- content here -->
		<div transition:slide={{ duration: 300, easing: sineInOut }}>
			<slot />
		</div>
	{/if}
</section>
